### ISSUE TITLE
How to login using python in websocket

### ISSUE THREAD

**Issue by skandakumardev** [the-firstock/pyfirstockconnect#11]

**Comment by Sharath-San** [comment]
client = firstockWebSockets.webSocketLogin()
ws = client.ws

Note

As soon as connection is done, a connection request should be sent with User id and login session id.
All input and output messages will be in json format.
what is the session id ?

**Comment by Sharath-San** [comment]
https://community.thefirstock.tech/t/how-to-login-using-python-in-websocket/85
