### ISSUE TITLE
Websocket Single Instance Issue

### ISSUE THREAD

**Issue by skandakumardev** [the-firstock/pyfirstockconnect#7]
``
Exception in thread WebSocketClient:
Traceback (most recent call last):
File “C:\Python311\Lib\threading.py”, line 1038, in _bootstrap_inner
self.run()
File “C:\Python311\Lib\threading.py”, line 975, in run
self._target(*self._args, **self._kwargs)
File “C:\Python311\Lib\site-packages\ws4py\websocket.py”, line 531, in run
self.terminate()
File “C:\Python311\Lib\site-packages\ws4py\websocket.py”, line 433, in terminate
self.closed(s.closing.code, s.closing.reason)
TypeError: WsClient.closed() takes 1 positional argument but 3 were given
``
Getting this error in websockets for one instance
 
Refer this query : https://community.thefirstock.tech/t/running-websocket/34

**Comment by Sharath-San** [comment]
Hi [@Venkat](https://community.thefirstock.tech/u/venkat) ,

Sorry for the delay, the issue has been fixed, please update the python package to 3.0.5 latest
